/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/Aside/index.vue')['default']
    AsideCollapseSwitch: typeof import('./src/components/AsideCollapseSwitch/index.vue')['default']
    DarkModeSwitch: typeof import('./src/components/DarkModeSwitch/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FullscreenSwitch: typeof import('./src/components/FullscreenSwitch/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    IEpDArrowLeft: typeof import('~icons/ep/d-arrow-left')['default']
    IEpDArrowRight: typeof import('~icons/ep/d-arrow-right')['default']
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IEpMoon: typeof import('~icons/ep/moon')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    Main: typeof import('./src/components/Main/index.vue')['default']
    MenuHomepage: typeof import('./src/components/MenuHomepage/index.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
